spring:
  application:
    name: matchmaking-service
  cloud:

  config:
    import: configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/